# Generated by Django 4.2.4 on 2023-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_remove_budget_end_date_remove_budget_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='savings',
            field=models.ManyToManyField(blank=True, related_name='budgets', to='budget_app.savings'),
        ),
    ]
