# Generated by Django 4.2.4 on 2023-08-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_budget_user_savings_user_alter_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
