# Generated by Django 4.2.4 on 2023-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_alter_savings_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
